### ISSUE TITLE
Cannot spawn human

### ISSUE THREAD

**Issue by chakalakalakabumbum** [WildBamaBoy/spider-queen#274]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 01:05 17/04/2017
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at radixcore.util.RadixMath.getNumberInRange(RadixMath.java:24)
	at sq.core.SpiderCore.getRandomPlayerName(SpiderCore.java:434)
	at sq.entity.creature.EntityHuman.<init>(EntityHuman.java:70)
	at sq.gen.WorldGenFactory.handlePlaceholderCallback(WorldGenFactory.java:249)
	at sq.gen.WorldGenFactory.spawnStructureRelativeToPoint(WorldGenFactory.java:236)
	at sq.gen.WorldGenFactory.generate(WorldGenFactory.java:90)
	at sq.gen.WorldGenFactory.generate(WorldGenFactory.java:63)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:130)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4265959456 bytes (4068 MB) / 6138888192 bytes (5854 MB) up to 6138888192 bytes (5854 MB)
	JVM Flags: 4 total; -XX:MaxPermSize=3072m -Xms6144m -Xmx6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 127 mods loaded, 127 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	gondolamod{1.2.4} [GondolaMod] (minecraft.jar) 
	UCHIJAA	AKInternalCore{1.0.1} [AKInternalCore] (minecraft.jar) 
	UCHIJAA	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCHIJAA	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCHIJAA	OldModelLoader{1.0} [OldModelLoader] (minecraft.jar) 
	UCHIJAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAA	mod_ecru_MapleTree{1.1.32e} [MapleTree] ([1.7.10]MapleTree Forge v1.1.32e.jar) 
	UCHIJAA	heart{2.0.0} [Heart Health] ([MC1.7.X]Hearts-2.0.0.jar) 
	UCHIJAA	LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) 
	UCHIJAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAA	academy-craft{1.0.4} [Academy Craft] (AcademyCraft-1.0.4.jar) 
	UCHIJAA	DCsAppleMilk{1.7.10_2.9m_for1291} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.9m_for1291.jar) 
	UCHIJAA	AMTAddonTutorial{1.7.10_1.0a} [AddonTutorialforAMT] (AddonTutorial-forAMT2_1.0a.jar) 
	UCHIJAA	advancedgenetics{1.5.9} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.9.jar) 
	UCHIJAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAA	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.9m_for1291.jar) 
	UCHIJAA	asielib{0.2.7} [asielib] (AsieLib-1.7.10.zip) 
	UCHIJAA	backlytra{1.7.10-0.0.3} [Backlytra] (Backlytra-1.7.10-0.0.3.jar) 
	UCHIJAA	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
	UCHIJAA	bettervillages{0.4} [Better Villages Mod] (Better-Villages-Mod-1.7.10.jar) 
	UCHIJAA	BetterFoliage{2.0.14} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.14.jar) 
	UCHIJAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAA	championglove{1.18} [Champion Glove] (ChampionGlove-1.7.10-1.18.jar) 
	UCHIJAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJAA	clonecraft{3.0} [CloneCraft] (CloneCraft-vB3.0.13.-.MC1.7.10.jar) 
	UCHIJAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAA	cpc{1.7.x-r76.6c6e88f} [CreepyPastaCraft] (CreepyPastaCraft-1.7.x-r76.6c6e88f-universal.jar) 
	UCHIJAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAA	dldungeonsjdg{1.9.0} [Doomlike Dungeons] (DoomlikeDungeons-1.9.0-MC1.7.10.jar) 
	UCHIJAA	k4lib{1.7.10-0.1.57} [K4Lib] (k4lib-1.7.10-0.1.57-universal.jar) 
	UCHIJAA	doubleJump{1.7.10-0.1.14} [DoubleJump] (doubleJump-1.7.10-0.1.14-universal.jar) 
	UCHIJAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0.jar) 
	UCHIJAA	net.blacklab.lib{0.1.1.forge1121} [EBLib] (EBLib-0.1.1.forge1121.jar) 
	UCHIJAA	EnchantChanger{1.7.10-1.8.38} [EnchantChanger] (EnchantChanger-1.7.10-1.8.38.jar) 
	UCHIJAA	etfuturum{1.5.5} [Et Futurum] (Et Futurum-1.5.5.jar) 
	UCHIJAA	FN5728{1.7.x-0.0.2} [FN5728Guns] (FN5728Guns-1.7.x_0.0.2.jar) 
	UCHIJAA	Funnelmod{1.7.x-srg-1} [Funnelmod] (Funnel1.7.x.zip) 
	UCHIJAA	GollumCoreLib{2.0.0} [Gollum Core Lib] (GollumCoreLib-2.0.0-1.7.10.jar) 
	UCHIJAA	gravestonemod{1.7.10} [Gravestones] (GraveStones 1.7.10 -3.jar) 
	UCHIJAA	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	UCHIJAA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCHIJAA	GVCEntity{1.7.x-srg-1} [GVCEntity] (GVCGunsReversion1.7.x.5.0.α.1.zip) 
	UCHIJAA	GVCGuns{1.7.x-srg-1} [GVCGuns] (GVCGunsReversion1.7.x.5.0.α.1.zip) 
	UCHIJAA	helpfulvillagers{1.4.0b5} [Helpful Villagers] (helpfulvillagers-1.7.10-1.4.0b5.jar) 
	UCHIJAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAA	InfernalMobs{1.6.6} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAA	IronFist{1.3.1} [Iron Fist] (ironfist-1.3.1.jar) 
	UCHIJAA	LavaMonsters{2.2.1} [Lava Monsters] (LavaMonsters-1.7.10-2.2.1.jar) 
	UCHIJAA	lmmx{1.0} [lmmx] (littleMaidMobX-1.7.x_0.1.1.jar) 
	UCHIJAA	MMMLibX{1.7.x-srg-1} [MMMLibX] (littleMaidMobX-1.7.x_0.1.1.jar) 
	UCHIJAA	zabuton{1.0} [zabuton] (littleMaidMobX-1.7.x_0.1.1.jar) 
	UCHIJAA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHIJAA	LMMInf{1.7.x-srg-1} [LMMInf] (LMMInf1.7.10.0.zip) 
	UCHIJAA	Magic{1.7.10.3} [Magic_Mod] (Magic1.7.10.3_Forge10.13.4.1558.zip) 
	UCHIJAA	MaidWhistle{1.7.10} [MaidWhistle] (MaidWhistle-1.7.10_0.2.jar) 
	UCHIJAA	mceconomy2{2.5.4} [MCEconomy 2] (MCEconomy2-2.5.4.a-1.7.0.jar) 
	UCHIJAA	nolpfij_mobstatues{0.1.0} [mobstatues] (MobStatues-1.7.10-0.1.0.jar) 
	UCHIJAA	dropvillager{1.0} [dropvillager] (mod_VillagerMeat-1.7.10.zip) 
	UCHIJAA	cookedvillager{1.0} [CookedVillagerCore] (mod_VillagerMeat-1.7.10.zip) 
	UCHIJAA	villagerMeat{1.0} [villagerMeatCore] (mod_VillagerMeat-1.7.10.zip) 
	UCHIJAA	villager_smelt{1.0} [villager_smelt] (mod_VillagerMeat-1.7.10.zip) 
	UCHIJAA	modchulib{17a} [modchulib; for mc162_179] (ModchuLib_mc1_5_2-1_11_2-v17a.zip) 
	UCHIJAA	examplemod{1.0} [examplemod] (More Health Enchanted-1.7.10-6.3.jar) 
	UCHIJAA	morehealth{6.3} [More Health Forge] (More Health Enchanted-1.7.10-6.3.jar) 
	UCHIJAA	MorePistons{2.0.0} [More Pistons] (MorePistons-2.0.0-1.7.10.jar) 
	UCHIJAA	movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1.jar.zip) 
	UCHIJAA	mowziesmobs{1.2.9} [Mowzie's Mobs] (MowziesMobs-1.2.99.jar) 
	UCHIJAA	cfm{3.4.8} [ｧ9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAA	musiccraft{2.9.9.3} [MusicCraft] (musiccraft-2.9.9.3.jar) 
	UCHIJAA	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHIJAA	mwaw{1.7.10-0.0.7} [Elemental Witch Mod] (mwaw-0.0.7-1.7.10.jar) 
	UCHIJAA	Mystcraft{0.12.3.03} [Mystcraft] (mystcraft-1.7.10-0.12.3.03.jar) 
	UCHIJAA	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
	UCHIJAA	NGTLib{1.7.10.26} [NGTLib] (NGTLib1.7.10.26_Forge10.13.4.1558.zip) 
	UCHIJAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar.zip) 
	UCHIJAA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHIJAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJAA	PetBat{1.3.8} [Pet Bat] (PetBat-1.7.10.jar) 
	UCHIJAA	placeableitems{2.0.1} [Placeable Items Mod] (placeableitems-2.0.1.jar) 
	UCHIJAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCHIJAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
	UCHIJAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar.zip) 
	UCHIJAA	ResurrectionFeather{dummy164} [ResurrectionFeather] (ResurrectionFeather_mc1_5_2-1_11_2-v11b.zip) 
	UCHIJAA	RidingIndicatingRod{dummy164} [RidingIndicatingRod] (RidingIndicatingRod_mc1_5_2-1_11_2-v8a.zip) 
	UCHIJAA	rivalrebels{1.7.10Q} [Rival Rebels] (rivalrebels-1.7.10Q.jar) 
	UCHIJAA	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHIJAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAA	TofuCraft{2.1.6-MC1.7.10} [豆腐Craft (TofuCraft)] (TofuCraft-2.1.6-MC1.7.10.jar) 
	UCHIJAA	RTG{1.7.10-1.1.1.3} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.3.jar) 
	UCHIJAA	ShibainuMod{1.4.0} [ShibainuMod] (ShibainuMod_1.7.10_1.4.0.jar) 
	UCHIJAA	DCsShowcase{1.7.10_beta4} [ShowcaseAddon2_forMCEconomy2] (ShowcaseAddon2-1.7.10_beta4.jar) 
	UCHIJAA	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] (SlashBlade-mc1.7.10-r87.jar) 
	UCHIJAA	SpecialAI{1.1.2} [Special AI] (SpecialAI-1.7.10-1.1.2.jar) 
	UCHIJAA	SQ{1.7.10-1.1.0} [Spider Queen] (SpiderQueen-1.7.10-1.1.0-universal.jar) 
	UCHIJAA	statues{2.1.3} [Statues] (Statues-Mod-1.7.10.zip) 
	UCHIJAA	net.blacklab.sugarbiomeplus{1.0.1.forge1121} [SugarBiomeplus] (SugarBiomeplus-1.0.1.forge1121.jar) 
	UCHIJAA	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) 
	UCHIJAA	TameableArachneMod{1.1.6} [TameableArachneMod] (TameableArachne-1.7.10-1.1.6.jar) 
	UCHIJAA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJAA	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJAA	thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
	UCHIJAA	erebus{0.4.7} [Erebus] (TheErebus-0.4.7.jar) 
	UCHIJAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHIJAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAA	tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar) 
	UCHIJAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAA	aziasvendingmachine{Vending Machines Revamped} [Vending Machines Revamped] (VendingMachinesRevamped_1.1.0_1.7.10.jar) 
	UCHIJAA	chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)] (VillageInfoSSP-1.7.10-2.1.jar) 
	UCHIJAA	VillagerTweaks{1.1d} [VillagerTweaks] (VillagerTweaks-1.1d.jar) 
	UCHIJAA	VocaloidMod{2.0} [Vocaloid Mod] (VocaloidMod-1.7.10-2.0.2_2.jar) 
	UCHIJAA	WLM{1.4.3} [The Wasteland Mod] (Wasteland mod-1.4.4.jar) 
	UCHIJAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAA	yarr_cutemobmodels{1.0.9} [Cute Mob Models] (yarrcutemobmodels-1.0.9-1.7.10.jar) 
	UCHIJAA	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.1.2-240
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.0 NVIDIA 376.33
	OpenGlRenderer: GeForce GTX 850M/PCIe/SSE2

**Comment by chakalakalakabumbum** [comment]
Seemed like when i play minecraft off-line, Spider queen mod cannot obtain player skins from the network, which make human unable to spawn.
